### ISSUE TITLE
Can Submit Numbers

### ISSUE THREAD

**Issue by antonnicolaa47** [janinavelasco9/phillips-wedding#1]
Can submit numbers in "Will you be attending?" and First Name and Last Name fields

**Comment by janinavelasco9** [comment]
fixeddddddddddd.

**Comment by antonnicolaa47** [comment]
<img width="814" alt="screen shot 2016-10-31 at 1 47 34 pm" src="https://cloud.githubusercontent.com/assets/23153927/19864928/9ca48672-9f70-11e6-835e-77f06d924ba6.png">

looks good
