### ISSUE TITLE
Validation error duplicating when submitting multiple times

### ISSUE THREAD

**Issue by antonnicolaa47** [janinavelasco9/phillips-wedding#10]
Multiple Browsers for radio buttons only:

![screen shot 2016-10-31 at 1 44 46 pm](https://cloud.githubusercontent.com/assets/23153927/19864801/38d8d21a-9f70-11e6-91e8-54ad846f6de9.png)

**Comment by janinavelasco9** [comment]
fixed.

**Comment by antonnicolaa47** [comment]
loooooks goooood
