### ISSUE TITLE
Remove "We can't wait to celebrate with you!" line

### ISSUE THREAD

**Issue by antonnicolaa47** [janinavelasco9/phillips-wedding#11]
When "No" is selected for the RSVP the person will get the "We can't wait to celebrate with you!" line.

Just remove that line and leave the mother's names and the "Thank you for RSVPing!" line

**Comment by janinavelasco9** [comment]
done.

**Comment by antonnicolaa47** [comment]
looks goooood
![Uploading Screen Shot 2016-11-16 at 1.49.20 PM.png…]()
