### ISSUE TITLE
Menu Weirdness

### ISSUE THREAD

**Issue by antonnicolaa47** [janinavelasco9/phillips-wedding#3]
Menu/Header Links not showing when you do the following:

Shrink screen, click on menu, expand screen

<img width="1196" alt="screen shot 2016-10-30 at 1 34 13 pm" src="https://cloud.githubusercontent.com/assets/23153927/19838437/94c6c396-9ea5-11e6-86a7-bb0292668b7b.png">

**Probably don't need to fix it because I doubt anyone will do this, but just incase.**

**Comment by janinavelasco9** [comment]
yeahhh i knew this was an issue, i think ill fix it last. 
because i don't think anyone would do that.

**Comment by janinavelasco9** [comment]
fixed this b.

**Comment by antonnicolaa47** [comment]
still seeing this...

**Comment by janinavelasco9** [comment]
fixedddddd.......

**Comment by antonnicolaa47** [comment]
looks gooooood
