### ISSUE TITLE
Required Text Area Differences 

### ISSUE THREAD

**Issue by antonnicolaa47** [janinavelasco9/phillips-wedding#4]
Differences in required text areas:
Did you want the outline on all browsers?

Firefox:
<img width="770" alt="screen shot 2016-10-30 at 1 36 33 pm" src="https://cloud.githubusercontent.com/assets/23153927/19838454/ef975d58-9ea5-11e6-8159-0306f12054a7.png">

Chrome:
<img width="783" alt="screen shot 2016-10-30 at 1 36 37 pm" src="https://cloud.githubusercontent.com/assets/23153927/19838456/f0d2dbd4-9ea5-11e6-95c5-cbc887736e3b.png">

**Comment by janinavelasco9** [comment]
![screen shot 2016-10-30 at 6 23 32 pm](https://cloud.githubusercontent.com/assets/23013396/19840526/190a4362-9ece-11e6-82a2-3a9ec4bce561.png)

weird. i see this.

**Comment by antonnicolaa47** [comment]
this looks good after your changes
