### ISSUE TITLE
THIS IS A SUGGESTION FOR "ARE YOU ATTENDING"

### ISSUE THREAD

**Issue by antonnicolaa47** [janinavelasco9/phillips-wedding#5]
I feel like the "Are you attending" question should be a radio button so people can't write in "Maybe"

If you still want to give the option to adding a comment maybe add a text area.

**Comment by janinavelasco9** [comment]
agreed. done.
i added checkboxes but im gonna add an issue to validate the checkboxes, gotta write some JS for that.

**Comment by janinavelasco9** [comment]
this is fixed.

**Comment by antonnicolaa47** [comment]
looks good
