### ISSUE TITLE
THIS IS A SUGGESTION FOR "DIETARY NEEDS"

### ISSUE THREAD

**Issue by antonnicolaa47** [janinavelasco9/phillips-wedding#6]
Maybe you should get rid of this text area or just make it a generic "comment" section.

I am assuming you are doing a buffet for the shower so you shouldn’t have to worry about dietary needs since people can have the option to pick what they want. Also, people can get crazy with this kind of question and I dont want you to feel obligated to solve for people's gluten allergies, etc.

**Comment by janinavelasco9** [comment]
done.

**Comment by antonnicolaa47** [comment]
looks good
