### ISSUE TITLE
Safari - On Submit RSVP

### ISSUE THREAD

**Issue by antonnicolaa47** [janinavelasco9/phillips-wedding#7]
SAFARI ONLY:
Validation for Submitting empty RSVP is opening in a new window.
Steps to reproduce:
Click Submit with empty fields and you should see the following:

<img width="781" alt="screen shot 2016-10-30 at 1 47 39 pm" src="https://cloud.githubusercontent.com/assets/23153927/19838527/abb5c424-9ea7-11e6-92d6-d0f9d88d2b09.png">

<img width="648" alt="screen shot 2016-10-30 at 1 47 24 pm" src="https://cloud.githubusercontent.com/assets/23153927/19838528/ad798322-9ea7-11e6-8022-82e1b0569bbd.png">

**Comment by janinavelasco9** [comment]
fixed this.

**Comment by antonnicolaa47** [comment]
this looks good
