### ISSUE TITLE
IE Null for Radio Buttons

### ISSUE THREAD

**Issue by antonnicolaa47** [janinavelasco9/phillips-wedding#9]
Seeing Null when submitting empty fields for radio buttons

![screen shot 2016-10-31 at 1 26 36 pm](https://cloud.githubusercontent.com/assets/23153927/19864747/f47e7bba-9f6f-11e6-811e-227c4a51a9b5.png)

**Comment by janinavelasco9** [comment]
i think i fixed this with the radio button validation issue. not sure.
...can't reproduce.

**Comment by antonnicolaa47** [comment]
<img width="811" alt="screen shot 2016-11-16 at 1 53 24 pm" src="https://cloud.githubusercontent.com/assets/23153927/20361104/5177bb9c-ac04-11e6-96f3-841809b4f8b8.png">

looks good
